"use client";

import { useMemo, useState } from "react";

type Screen = "home" | "results" | "profile" | "request" | "status" | "feedback" | "admin";

const professionals = [
  { id: 1, name: "Sunita", initials: "SU", rating: "4.9", reviews: 18, experience: "8 years", match: "Exact time match", time: "7:30–8:15 AM", price: "₹3,200", services: "House cleaning + utensils", accent: "plum", note: "Works in your phase" },
  { id: 2, name: "Poonam", initials: "PO", rating: "4.8", reviews: 11, experience: "6 years", match: "30 min from preferred time", time: "8:00–8:45 AM", price: "₹3,000", services: "House cleaning + utensils", accent: "teal", note: "Recently active" },
  { id: 3, name: "Rekha", initials: "RE", rating: "New", reviews: 0, experience: "5 years", match: "Exact time match", time: "7:30–8:15 AM", price: "₹2,900", services: "House cleaning + utensils", accent: "ochre", note: "Identity verified" },
];

const screenOrder: Screen[] = ["home", "results", "profile", "request", "status"];

export default function Home() {
  const [screen, setScreen] = useState<Screen>("home");
  const [selectedId, setSelectedId] = useState(1);
  const [language, setLanguage] = useState<"EN" | "हिं">("EN");
  const [notice, setNotice] = useState("");
  const selected = useMemo(() => professionals.find((p) => p.id === selectedId) ?? professionals[0], [selectedId]);
  const mainScreen = screenOrder.includes(screen) ? screen : "home";
  const goProfile = (id: number) => { setSelectedId(id); setScreen("profile"); window.scrollTo({ top: 0, behavior: "smooth" }); };

  return (
    <main className="site-shell">
      <header className="topbar">
        <button className="brand" onClick={() => setScreen("home")} aria-label="Nivasa home"><span className="brand-mark">N</span><span>Nivasa</span><small>beta</small></button>
        <div className="header-actions"><button className="quiet-button feedback-shortcut" onClick={() => setScreen("feedback")}>Share feedback</button><button className="language-toggle" onClick={() => setLanguage(language === "EN" ? "हिं" : "EN")}>{language === "EN" ? "हिंदी" : "English"}</button><button className="account-button" aria-label="Account">SM</button></div>
      </header>

      {mainScreen !== "home" && <nav className="stepbar" aria-label="Booking progress">{screenOrder.map((item, index) => { const active = screenOrder.indexOf(mainScreen); return <button key={item} className={index <= active ? "step complete" : "step"} onClick={() => index <= active && setScreen(item)}><span>{index + 1}</span>{item === "home" ? "Need" : item === "results" ? "Matches" : item === "profile" ? "Profile" : item === "request" ? "Request" : "Hire"}</button>; })}</nav>}

      {screen === "home" && <>
        <section className="hero">
          <div className="hero-copy"><p className="eyebrow">Omaxe New Chandigarh · Private beta</p><h1>Reliable home support,<br />chosen with confidence.</h1><p className="hero-subtitle">Compare identity-verified professionals by schedule, experience, reviews and their own listed price.</p><div className="trust-row"><span>✓ Identity checked</span><span>✓ Clear monthly pricing</span><span>✓ Mutual acceptance</span></div></div>
          <div className="search-card">
            <div className="search-heading"><div><p className="overline">Find a recurring professional</p><h2>Tell us what works for your home</h2></div><span className="beta-pill">Free for 7 days</span></div>
            <label className="field"><span>Service package</span><select defaultValue="combo"><option value="clean">House cleaning</option><option value="utensils1">Utensils · once daily</option><option value="utensils2">Utensils · twice daily</option><option value="combo">House cleaning + utensils once daily</option></select></label>
            <div className="field-grid"><label className="field"><span>Home size</span><select defaultValue="3bhk"><option>1–2 BHK</option><option value="3bhk">3 BHK</option><option>4+ BHK</option></select></label><label className="field"><span>Preferred time</span><select defaultValue="730"><option value="730">7:30 AM</option><option>8:00 AM</option><option>8:30 AM</option></select></label></div>
            <label className="field location-field"><span>Locality</span><div>Omaxe New Chandigarh <b>Confirmed</b></div></label>
            <button className="primary-button wide" onClick={() => setScreen("results")}>See available professionals <span>→</span></button><p className="fine-print">After the 7-day free trial, charges will apply to new professional introductions.</p>
          </div>
        </section>
        <section className="principles"><article><span>01</span><h3>Clear before contact</h3><p>See the work scope, recurring time and monthly price before sending a request.</p></article><article><span>02</span><h3>Choice on both sides</h3><p>You choose who to request. The professional reviews and accepts each household.</p></article><article><span>03</span><h3>A record you can rely on</h3><p>Confirmed hires reserve the recurring slot and unlock verified feedback over time.</p></article></section>
      </>}

      {screen === "results" && <section className="content-page results-page">
        <div className="page-heading-row"><div><p className="eyebrow">3 professionals match your requirement</p><h1>Choose the right fit for your home</h1><p>House cleaning + utensils · 3 BHK · preferred 7:30 AM</p></div><button className="outline-button" onClick={() => setScreen("home")}>Edit requirement</button></div>
        <div className="filter-row"><button className="filter active">Best match</button><button className="filter">Exact time</button><button className="filter">Rating 4.5+</button><button className="filter">Price</button></div>
        <div className="results-layout"><div className="profile-list">{professionals.map((person, index) => <article className="profile-card" key={person.id} onClick={() => goProfile(person.id)}><div className={`avatar ${person.accent}`}>{person.initials}</div><div className="profile-main"><div className="profile-title"><h2>{person.name}</h2><span className="verified">✓ Identity verified</span></div><p className="match-label">{index === 0 ? "Top match · " : ""}{person.match}</p><p className="service-line">{person.services}</p><div className="profile-meta"><span>★ {person.rating}{person.reviews > 0 ? ` (${person.reviews})` : ""}</span><span>{person.experience}</span><span>{person.note}</span></div></div><div className="profile-price"><strong>{person.price}</strong><span>/ month</span><small>{person.time}</small><button>View profile</button></div></article>)}</div>
          <aside className="match-explainer"><p className="overline">Why these matches?</p><h3>Designed around consistency</h3><ul><li><b>Schedule fit</b><span>Preferred or closest available time</span></li><li><b>Proximity</b><span>Distance and travel buffer checked privately</span></li><li><b>Quality</b><span>Reviews, reliability and experience</span></li></ul><p>Exact home addresses are never shown during discovery.</p></aside></div>
      </section>}

      {screen === "profile" && <section className="content-page profile-page"><button className="back-button" onClick={() => setScreen("results")}>← Back to matches</button><div className="profile-hero"><div className={`avatar large ${selected.accent}`}>{selected.initials}</div><div className="profile-identity"><div className="profile-title"><h1>{selected.name}</h1><span className="verified">✓ Identity verified</span></div><p>{selected.experience} of household work experience</p><div className="profile-meta large-meta"><span>★ {selected.rating}{selected.reviews ? ` from ${selected.reviews} reviews` : " · New on Nivasa"}</span><span>{selected.note}</span></div></div><div className="profile-quote"><p>Listed monthly salary</p><strong>{selected.price}</strong><span>House cleaning + utensils</span></div></div>
        <div className="detail-grid"><div className="detail-main"><section className="detail-section"><p className="overline">Your schedule match</p><h2>{selected.match}</h2><div className="time-card"><span>Every day</span><strong>{selected.time}</strong><small>Travel buffer checked before and after this slot</small></div></section><section className="detail-section"><p className="overline">Included work</p><h2>A clear, standardized scope</h2><div className="scope-grid"><div><b>House cleaning</b><span>Sweeping and mopping occupied indoor rooms and kitchen floor</span></div><div><b>Utensils · once daily</b><span>Routine household utensils from one daily visit cycle</span></div></div><p className="scope-note">Bathrooms, dusting, laundry, ironing and deep cleaning are not included in this package.</p></section><section className="detail-section reviews"><p className="overline">Resident feedback</p><h2>Trusted for consistency and care</h2><blockquote>“Punctual, communicates clearly and follows the agreed work scope.”<footer>Verified resident · 3 months of service</footer></blockquote></section></div>
          <aside className="booking-panel"><div className="panel-price"><strong>{selected.price}</strong><span>per month</span></div><div className="panel-line"><span>Package</span><b>Cleaning + utensils</b></div><div className="panel-line"><span>Schedule</span><b>{selected.time}</b></div><div className="panel-line"><span>Start date</span><b>26 Aug</b></div><button className="primary-button wide" onClick={() => setScreen("request")}>Request this professional</button><p>No payment is required during the 7-day beta. {selected.name} will review your exact package, time and approximate block before accepting.</p></aside></div>
      </section>}

      {screen === "request" && <section className="content-page narrow-page"><button className="back-button" onClick={() => setScreen("profile")}>← Back to profile</button><p className="eyebrow">Review your request</p><h1>Everything clear before you connect</h1><p className="page-intro">This is a request—not a confirmed hire. {selected.name} can accept or decline after reviewing the details below.</p><div className="review-card"><div className="review-person"><div className={`avatar ${selected.accent}`}>{selected.initials}</div><div><h2>{selected.name}</h2><span className="verified">✓ Identity verified</span></div><strong>{selected.price}<small>/month</small></strong></div><dl><div><dt>Package</dt><dd>House cleaning + utensils once daily</dd></div><div><dt>Home size</dt><dd>3 BHK</dd></div><div><dt>Recurring schedule</dt><dd>Every day · {selected.time}</dd></div><div><dt>Approximate location shared</dt><dd>Omaxe New Chandigarh · your exact flat remains private</dd></div><div><dt>Desired start</dt><dd>26 August</dd></div></dl><label className="consent"><input type="checkbox" defaultChecked /><span>I understand the included work and listed monthly salary.</span></label></div><div className="beta-notice"><span>7-day free beta</span><p>No platform charge or payment details are required. After the 7-day free trial, charges will apply to new professional introductions.</p></div><button className="primary-button wide" onClick={() => { setScreen("status"); setNotice(`Request sent to ${selected.name}`); }}>Send booking request</button></section>}

      {screen === "status" && <section className="content-page narrow-page status-page">{notice && <div className="toast">✓ {notice}</div>}<p className="eyebrow">Booking status</p><h1>Your request has been accepted</h1><p className="page-intro">Speak or meet to confirm the fit. The recurring slot is reserved only after both of you confirm the hire.</p><div className="status-card"><div className="status-top"><div className={`avatar ${selected.accent}`}>{selected.initials}</div><div><h2>{selected.name}</h2><p>House cleaning + utensils · {selected.time}</p></div><span className="status-pill">Accepted</span></div><div className="timeline"><div className="done"><i>✓</i><span><b>Request sent</b><small>Today · 9:12 AM</small></span></div><div className="done"><i>✓</i><span><b>{selected.name} accepted</b><small>Today · 10:04 AM</small></span></div><div className="current"><i>3</i><span><b>Speak or meet</b><small>Contact is now available during the free beta</small></span></div><div><i>4</i><span><b>Confirm the hire</b><small>Both parties confirm to reserve the slot</small></span></div></div><div className="contact-strip"><div><span>Phone</span><b>••••• 4821</b></div><button className="outline-button">Call {selected.name}</button></div><button className="primary-button wide" onClick={() => setNotice(`Hire confirmation sent to ${selected.name}`)}>Confirm I am hiring {selected.name}</button></div><div className="support-row"><button onClick={() => setScreen("feedback")}><b>Share beta feedback</b><span>Tell us what felt clear or difficult →</span></button><button onClick={() => setScreen("feedback")}><b>Report a problem</b><span>Cancellation, no-show or incorrect details →</span></button></div></section>}

      {screen === "feedback" && <section className="content-page narrow-page feedback-page"><button className="back-button" onClick={() => setScreen(mainScreen === "home" ? "home" : "status")}>← Back</button><p className="eyebrow">Private beta</p><h1>Help us make hiring feel better</h1><p className="page-intro">This feedback is about the Nivasa experience. It is separate from a review of a professional.</p><div className="feedback-card"><fieldset><legend>What would you like to tell us?</legend><div className="choice-grid"><label><input type="radio" name="type" defaultChecked /> Product feedback</label><label><input type="radio" name="type" /> Professional did not arrive</label><label><input type="radio" name="type" /> Professional cancelled</label><label><input type="radio" name="type" /> Information was incorrect</label></div></fieldset><label className="field"><span>How easy was the experience?</span><div className="score-row">{[1,2,3,4,5].map(n => <button key={n}>{n}</button>)}</div></label><label className="field"><span>Tell us what happened</span><textarea placeholder="Your feedback helps us improve the beta…" rows={5}></textarea></label><label className="consent"><input type="checkbox" defaultChecked /><span>You may contact me about this feedback.</span></label><button className="primary-button wide" onClick={() => { setNotice("Thank you—your feedback has been recorded"); setScreen("status"); }}>Submit feedback</button></div><div className="no-show-note"><b>If a professional does not arrive</b><p>We will record the incident, contact both parties and reopen your requirement so you can review other available profiles. The beta does not promise an immediate replacement.</p></div><button className="admin-link" onClick={() => setScreen("admin")}>Founder view: open beta operations queue →</button></section>}

      {screen === "admin" && <section className="content-page admin-page"><button className="back-button" onClick={() => setScreen("feedback")}>← Resident experience</button><div className="page-heading-row"><div><p className="eyebrow">Founder operations</p><h1>Beta resolution queue</h1><p>One lightweight place to resolve the exceptions that can damage trust.</p></div><span className="live-pill">3 open items</span></div><div className="admin-stats"><article><span>Open</span><strong>3</strong></article><article><span>Median first response</span><strong>18 min</strong></article><article><span>Resolved today</span><strong>7</strong></article><article><span>No-shows this week</span><strong>2</strong></article></div><div className="queue-table"><div className="queue-head"><span>Issue</span><span>People</span><span>Next action</span><span>Status</span></div><div className="queue-row urgent"><span><b>No-show reported</b><small>Today · 8:22 AM</small></span><span>Sunita · Shifia</span><span>Contact both parties; reopen requirement</span><button>Open</button></div><div className="queue-row"><span><b>Cancellation before meeting</b><small>Yesterday · 6:40 PM</small></span><span>Poonam · Neha</span><span>Confirm reason; restore introduction credit</span><button>Open</button></div><div className="queue-row"><span><b>Duplicate professional profile</b><small>Yesterday · 4:15 PM</small></span><span>Rekha / Rekha K.</span><span>Merge after mobile verification</span><button>Review</button></div></div><div className="admin-principle"><b>MVP decision</b><p>Include reporting, case status and a compact administrator queue. Do not build an elaborate ticketing system or promise replacement dispatch for the seven-day beta.</p></div></section>}

      <footer className="site-footer"><span>Nivasa · Working-name prototype</span><button onClick={() => setScreen("admin")}>Founder operations</button><span>Omaxe private beta</span></footer>
    </main>
  );
}
